export function handleHelp(): string {
  return [
    '📖 *BANTUAN STIKER BOT*:',
    '',
    '• *Stiker Teks*:',
    '  !stiker <teks> → Buat stiker teks polos',
    '  !stiker teks <teks> → Paksa mode teks (meski me-reply foto/video)',
    '  Reply teks lalu !stiker quote → Stiker kutipan berbingkai nama',
    '  Reply teks lalu !stiker bubble → Stiker bubble chat WhatsApp',
    '  !ttp <teks> → Stiker teks dengan gradien warna',
    '  !attp <teks> → Stiker teks animasi warna-warni',
    '',
    '• *Stiker Media*:',
    '  Reply / kirim foto lalu !stiker → Stiker foto standar',
    '  Reply / kirim foto lalu !stiker full → Stiker foto penuh (contain)',
    '  Reply / kirim foto lalu !stiker crop → Stiker foto terpotong (cover)',
    '  Reply / kirim foto lalu !stiker circle → Stiker foto bulat',
    '  Reply / kirim foto lalu !stiker meme <atas> | <bawah> → Stiker meme',
    '  Reply / kirim video (maks 10 dtk) lalu !stiker → Stiker video bergerak',
    '',
    '• *Konversi*:',
    '  Reply stiker statis lalu !toimg → Ubah stiker jadi gambar',
    '  Reply stiker bergerak lalu !togif → Ubah stiker jadi video',
    '',
    '• *Pengaturan & Utilitas*:',
    '  !prefix <simbol> → Ubah prefix bot (grup: khusus admin)',
    '  !menu → Lihat daftar perintah',
    '  !help → Bantuan penggunaan',
    '  !ping → Cek status dan latensi bot',
  ].join('\n');
}
